### ISSUE TITLE
Make it possible to write plugins

### ISSUE THREAD

**Issue by zoffixznet** [XTaTIK/XTaTIK#64]
Somehow.... What we need right now is offer purchases made to $company's website, which will require some custom code to be used in the cart system.

How do we include such type of stuff?

**Comment by cassi42** [comment]
I finished PayPal cart plugin in 2932a49c26f5254a13605f75f556d70554bea607 

Any custom checkout can now be supported. Custom plugins would need to be named `XTaTIK::Plugin::Cart::FOO` and override `checkout` and possibly `thank_you` methods. The two methods are called from two separate pages. You can collect form data on one and post to the other. The plugin gets the controller object in both methods which gives lotsa firepower.
